groups:
- name: cpu-node
  rules:
  - record: job_instance_mode:vendor_web_instrumentation_documents_endpoint_timeouts_total:avg_rate5m
    expr: avg by (job, instance, mode) (rate(vendor_web_instrumentation_documents_endpoint_timeouts_total[5m]))